1. Max score = 10
Berilgan butun son n.
Agar son palindrome bo‘lsa True, aks holda False qaytarsin.

Input: 121
Output: True

Input: 1231
Output: False


2. Max score = 15
Berilgan string s.
Qavslar to‘g‘ri yopilganligini tekshiring.

To`g`ri yopilish: ()  {}  []

Input: "()[]{}"
Output: True

Input: "(]"
Output: False



3. Max score = 15
Berilgan butun sonlardan iborat list nums va butun son k.
listni o‘ng tomonga k marta aylantiring.

O‘ng tomonga aylantirish degani:
listning oxiridagi element(lar) list boshiga o‘tkaziladi qolgan elementlar o‘ngga siljiydi.

⚠️ Muhim:
k list uzunligidan katta bo‘lishi mumkin.

Input:
nums = [1,2,3,4,5,6,7]
k = 3

Output:
[5,6,7,1,2,3,4]

Input:
nums = [10,20,30,40]
k = 1

Output:
[40,10,20,30]




4. Max score = 20
Python (Pandas) yordamida muzlatkichdagi ingredientlar bilan to‘liq tayyorlash mumkin bo‘lgan barcha taomlarni aniqlang.
   Agar biror taom uchun kerakli ingredientlardan bittasi ham yetishmasa, u taom natijaga kiritilmasin.

recipe = pd.DataFrame({
    "recipe_name": ["hotdog","hotdog","pilov","pilov","pilov","pizza","pizza","pizza"],
    "ingredient_id": [1,2,3,4,5,6,7,8],
    "ingredient_name": ["sausage","bread","rice","carrot","meat","flour","tomato","cheese"]
})

fridge = pd.DataFrame({
    "ingredient_id": [1,2,3,4,6],
    "ingredient_name": ["sausage","bread","rice","carrot","flour"]
})

Expected output: [hotdog]



task 5. Max score = 25

 You have a dataset (customer_orders.csv) containing information about customer orders. The dataset has the following columns:

 OrderID: Unique identifier for each order.
 CustomerID: Unique identifier for each customer.
 Product: Name of the product ordered.
 Quantity: Number of units ordered.
 Price: Price per unit.

 Tasks:

 1)Group the data by CustomerID and filter out customers who have made less than 20 orders.
 2)Identify customers who have ordered products with an average price per unit greater than $120.

In [10]:
# Task1
n=12321
m = str(n)
if m==m[::-1]:
    print("True")
else:
    print("False")

True

In [96]:
# Task 2
def check_brackets(s):
    brackets = {'(': ')', '[': ']', '{': '}'}
    stack = []
    for char in s:
        if char in brackets.values():
            stack.append(char)
        elif char in brackets.keys():
            if stack and stack[-1] == brackets[char]:
                stack.pop()
            else:
                return False
check_brackets("()")

False

In [97]:
# Task3
def shift_list(nums, k):
    return nums[k+1:] + nums[:k+1]
shift_list([1,2,3,4,5,6,7], 3)

[5, 6, 7, 1, 2, 3, 4]

In [53]:
# task 5
import pandas as pd
df = pd.read_csv('customer_orders.csv')
# 1st task
df['Total_orders'] = df.groupby('CustomerID')['Quantity'].transform('sum')
customers_more_orders = df[df['Total_orders'] > 20]
customers_more_orders
# 2nd task
df['Average_price'] = df.groupby('CustomerID')['Price'].transform('mean')
customer_higher_price = df[df['Average_price'] > 120]
customer_higher_price

    OrderID  CustomerID              Product  Quantity  Price
0         1         101               Laptop         2    800
1         2         102           Headphones         1    150
2         3         103           Smartphone         3    400
3         4         101  External Hard Drive         2     80
4         5         102             Backpack         1     40
..      ...         ...                  ...       ...    ...
95       96         103              Blender         1     60
96       97         104          Sport Shoes         2     40
97       98         105        Comforter Set         1     45
98       99         101     Wireless Earbuds         2    120
99      100         102       Gaming Console         1    400

[100 rows x 5 columns]

In [69]:
df['Total_orders'] = df.groupby('CustomerID')['Quantity'].transform('sum')
customers_more_orders = df[df['Total_orders'] > 20]
customers_more_orders

    OrderID  CustomerID              Product  Quantity  Price  Total_orders
0         1         101               Laptop         2    800            27
1         2         102           Headphones         1    150            25
2         3         103           Smartphone         3    400            28
3         4         101  External Hard Drive         2     80            27
4         5         102             Backpack         1     40            25
..      ...         ...                  ...       ...    ...           ...
95       96         103              Blender         1     60            28
96       97         104          Sport Shoes         2     40            27
97       98         105        Comforter Set         1     45            21
98       99         101     Wireless Earbuds         2    120            27
99      100         102       Gaming Console         1    400            25

[100 rows x 6 columns]

In [75]:
df['Average_price'] = df.groupby('CustomerID')['Price'].transform('mean')
customer_higher_price = df[df['Average_price'] > 120]
customer_higher_price

,OrderID,CustomerID,Product,Quantity,Price,Total_orders,Average_price
1,2,102,Headphones,1,150,25,138.095238
4,5,102,Backpack,1,40,25,138.095238
5,6,104,Tablet,2,300,27,169.750000
8,9,102,Smart TV,1,1000,25,138.095238
9,10,104,Coffee Maker,1,50,27,169.750000
12,13,104,Kitchen Scale,1,20,27,169.750000
14,15,102,Blender,2,60,25,138.095238
16,17,104,Cookware Set,1,60,27,169.750000
19,20,102,Summer Dress,2,30,25,138.095238
21,22,104,Comforter Set,1,45,27,169.750000
24,25,102,Desk Lamp,1,25,25,138.095238
26,27,104,Sweater,2,35,27,169.750000
29,30,102,Casual Shoes,1,30,25,138.095238
31,32,104,Sport Shoes,2,40,27,169.750000
34,35,102,Jeans,1,30,25,138.095238
36,37,104,Hoodie,1,25,27,169.750000
39,40,102,Toaster,1,25,25,138.095238
41,42,104,Bookshelf,1,80,27,169.750000
44,45,102,Backpack,1,40,25,138.095238
46,47,104,Smart TV,1,1000,27,169.750000
49,50,102,Wireless Mouse,1,25,25,138.095238
51,52,104,Gaming Console,1,400,27,169.750000
54,55,102,Smartphone,2,400,25,138.095238
56,57,104,Desk Lamp,1,25,27,169.750000
59,60,102,Blender,1,60,25,138.095238
61,62,104,Steam Iron,2,30,27,169.750000
64,65,102,Formal Shirt,2,35,25,138.095238
66,67,104,Jeans,1,30,27,169.750000
69,70,102,Summer Dress,1,30,25,138.095238
71,72,104,Blu-ray Player,1,70,27,169.750000
74,75,102,Drone,1,300,25,138.095238
76,77,104,Coffee Table,2,100,27,169.750000
79,80,102,Denim Jacket,1,45,25,138.095238
81,82,104,Sunglasses,2,15,27,169.750000
84,85,102,Desk Chair,1,75,25,138.095238
86,87,104,Smart TV,1,1000,27,169.750000
89,90,102,Backpack,1,40,25,138.095238
91,92,104,Jeans,1,30,27,169.750000
94,95,102,Fitness Tracker,1,60,25,138.095238
96,97,104,Sport Shoes,2,40,27,169.750000
99,100,102,Gaming Console,1,400,25,138.095238

In [76]:
# Task 4
import pandas as pd
recipe = pd.DataFrame({
    "recipe_name": ["hotdog","hotdog","pilov","pilov","pilov","pizza","pizza","pizza"],
    "ingredient_id": [1,2,3,4,5,6,7,8],
    "ingredient_name": ["sausage","bread","rice","carrot","meat","flour","tomato","cheese"]
})

fridge = pd.DataFrame({
    "ingredient_id": [1,2,3,4,6],
    "ingredient_name": ["sausage","bread","rice","carrot","flour"]
})

recipe_ingredients = recipe.groupby("recipe_name")["ingredient_id"].apply(set)
fridge_ingredients = set(fridge["ingredient_id"])

available_recipes = [name for name, ingredients in recipe_ingredients.items() if
                     ingredients.issubset(fridge_ingredients)]

print(available_recipes)

['hotdog']